FROM ktzr/python-pip
COPY docker/Dockerfile-rst-lint /
COPY . .
RUN pip install -U pip rstcheck \
    && echo "\n++++++++++++++" \
    && echo "Launch lint" \
    && echo "++++++++++++++\n" \
    && rstcheck **/*.rst \
    && echo "\n++++++++++++++" \
    && echo "End lint" \
    && echo "++++++++++++++\n"

