---
# source: https://github.com/gantsign/ansible-role-atom
# https://github.com/gantsign/ansible-role-visual-studio-code-extensions
- name: install vscode key (apt)
  become: yes
  apt_key:
    url: 'https://packages.microsoft.com/keys/microsoft.asc'
    state: present

- name: install VS Code repo (apt)
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    filename: vscode
    state: present

- name: install VS Code (apt)
  become: yes
  apt:
    name: "code"
    state: present

