---
- name: install zsh
  become: yes
  apt:
    name: zsh
    state: latest

- name: install zsh
  become: yes
  apt:
    name: curl
    state: latest

- name: install oh-my-zsh
  become: yes
  shell: sh -c "$(curl -fsSL {{ config.oh_my_zsh_url | default('https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh') }})"
  ignore_errors: True

- name: check z.sh in ~/.bashrc
  become: false
  lineinfile:
    path: ~/.bashrc
    line: 'zsh'
    state: present

- name: get z.sh
  become: false
  get_url:
    url: "{{ config.z_dot_sh_url | default('https://raw.githubusercontent.com/rupa/z/master/z.sh') }}"
    dest: ~/ 

- name: check z.sh in ~/.bashrc
  become: false
  lineinfile:
    path: ~/.bashrc
    line: 'source ~/z.sh'
    state: present

- name: check z.sh in ~/.zshrc
  become: false
  lineinfile:
    path: ~/.zshrc
    line: 'source ~/z.sh'
    state: present

