---
- name: 'install docker dependancies'
  become: yes
  package:
    state: "absent"
    name:
      - "docker"
      - "docker-engine"
      - "docker.io"
      - "containerd"
      - "runc"
- name: 'install docker dependancies'
  become: yes
  package:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
- name: "install docker gpg key"
  become: yes
  shell: >
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
- name:
  become: yes
  shell: >
    echo \
      "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
      $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list
  register: test
- import_tasks: tasks/apt_update.yml
- name: 'install docker'
  become: yes
  package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
