---
- name: install git
  apt:
    name: git
- name: make gitconfig
  template:
    src: templates/.gitconfig.j2
    dest: "/home/{{config.user}}/.gitconfig"
    owner: "{{config.user}}"
    group: "{{config.user}}"
    mode: 0644
