---
# source: https://github.com/bt5e/ansible-role-docker-non-root-user/blob/master/tasks/main.yml
- name: Create docker group
  group:
    name: docker
    state: present
  become: yes
- include: subtask-non_root_docker_user.yml
  with_items: "{{ non_root_docker_users }}"
  loop_control:
    loop_var: user
