- name: install jre
  become: yes
  package:
    name: openjdk-11-jre
    state: present
- name: create soft dir
  file:
    path: ~/software
    state: directory
    mode: '0755'
- name: get cgoban
  get_url:
    url: http://files.gokgs.com/javaBin/cgoban.jar
    dest: ~/software/cgoban.jnlp