dist: xenial # needed to use python 3.7
language: python
branches:
  only:
    - master
python:
  - 3.7
install:
  - pip install -U pip
  - cd 000-docs
  - pip install -r requirements.txt # install the required packages
  #- go get github.com/errata-ai/vale # install vale
script:
  - skip # Travis requires a `script` property, but we do not need it
stages:
  #- build and test
  - deploy
jobs:
  include:
    #- stage: build and test
    #  name: Build
    #  script: 
    #    - sphinx-build -nWT -b dummy source _build/html
    #  skip-cleanup: true
    #- script: vale source # run vale
    #  name: Test
    - stage: deploy
      name: Deploy to GitHub Pages
      if: (branch = master) # only deploy if merging on master
      script: 
        - make html
        - ls build/html
        - ls build/html/_static
        - ls build/html/_static/js
        - ls build/html/_static/css
        - touch build/html/.nojekyll
      deploy:
        provider: pages # deploy on github pages
        skip_cleanup: true
        github_token: "$token" # defined via the Travis interface
        local_dir: 000-docs/build/html