---
- name: Create "{{ ldap_server_data_dir }}"
  file:
    path: "{{ ldap_server_data_dir }}"                                                         
    state: directory
    mode: 0755
  tags:
    - ldap
    - ldap-server

- name: Create "{{ ldap_server_conf_dir }}"
  file:
    path: "{{ ldap_server_conf_dir }}"                                                         
    state: directory
    mode: 0755
  tags:
    - ldap
    - ldap-server

- name: systemd ldap server
  template:
    src: ldap-server.service.j2
    dest: /etc/systemd/system/ldap-server.service
  notify: restart ldap-server
  tags:
    - ldap
    - ldap-server

- name: enable ldap-server service
  systemd:
    name: ldap-server
    enabled: true
    state: started
    daemon_reload: true
  tags:
    - ldap
    - ldap-server

- name: systemd ldap-admin
  template:
    src: ldap-admin.service.j2
    dest: /etc/systemd/system/ldap-admin.service
  notify: restart ldap-admin
  tags:
    - ldap
    - ldap-admin

- name: enable ldap-admin service
  systemd:
    name: ldap-admin
    enabled: true
    state: started
    daemon_reload: true
  tags:
    - ldap
    - ldap-admin
