version: '3'
services:
  neo4j:
    image: 'neo4j:3.5'
    ports:
      - '7474:7474'
      - '7473:7473'
      - '7687:7687'
    volumes:
      - './neo4j_data:/data'
      - './neo4j_log:/log'
      - './neo4j_import:/var/lib/neo4j/import'
      - './neo4j_plugins:/plugins'
    environment:
      NEO4J_AUTH: "neo4j/test"
volumes:
  neo4j_data: 
    driver: local
  neo4j_log: 
    driver: local
  neo4j_import: 
    driver: local
  neo4j_plugins: 
    driver: local

