---
- name: "Create {{ gitlab_omnibus_data_dir }}"
  file:
    path: "{{ gitlab_omnibus_data_dir }}"
    state: directory
    mode: 0755
  tags:
    - gitlab-omnibus
- name: systemd gitlab-omnibus service
  template:
    src: gitlab-omnibus.service.j2
    dest: /etc/systemd/system/gitlab-omnibus.service
  notify: restart gitlab-omnibus
  tags:
    - gitlab-omnibus
- name: gitlab-omnibus config
  template:
    src: gitlab.rb.j2
    dest: "{{ gitlab_omnibus_config_dir }}"
  notify: restart gitlab-omnibus
  tags:
    - gitlab-omnibus
- name: enable gitlab-omnibus service
  systemd:
    name: gitlab-omnibus
    enabled: true
    state: started
    daemon_reload: true
  tags:
    - gitlab-omnibus
