---
- when: kubectl_install | bool
  block:
  - name: Download kubectl binary
    get_url:
      url: "https://storage.googleapis.com/kubernetes-release/release/v{{ kubectl_version }}/bin/{{ kubectl_os }}/{{ kubectl_arch }}/kubectl"
      checksum: "{{ kubectl_checksum_binary }}"
      dest: "{{ kubectl_tmp_directory }}"
    tags:
      - kubectl

  - name: Copy kubectl binary to destination directory
    copy:
      src: "{{ kubectl_tmp_directory }}/kubectl"
      dest: "{{ kubectl_path_to_install }}/kubectl"
      mode: "+x"
      remote_src: yes
    become: yes

  - name: "add kubectl path"
    import_role:
      name: "env_vars"
    vars:
      env_vars_list:
        - "export PATH=$PATH:{{ kubectl_path_to_install }}"

  - name: "add kubectl alias to know alias result"
    import_role:
      name: "env_alias"
    vars:
      env_alias_list:
        - "function kubectl() { echo \"+ kubectl $@\">&2; command kubectl $@; }"
