---
- when: helm_install | bool
  block:
  - name: "create soft dir: {{ helm_path_to_install }}"
    file:
      path: "{{ helm_path_to_install }}"
      state: directory
      mode: '0755'
      recurse: yes

  - name: Download helm
    ansible.builtin.unarchive:
      src: "{{ helm_download_url }}"
      dest: "{{ helm_path_to_install }}"
      remote_src: yes
      extra_opts:
        - linux-amd64/helm

  - name: "Add {{ helm_path_to_install }} to path"
    import_role:
      name: "env_vars"
    vars:
      env_vars_list:
        - "export PATH=$PATH:{{ helm_path_to_install }}/linux-amd64/"
