---
- when: android_studio_install
  block:
  - name: "create soft dir: {{ android_studio_path_to_install }}"
    become: yes
    ansible.builtin.file:
      path: "{{ android_studio_path_to_install }}"
      state: directory
      mode: "0755"
      recurse: yes
      owner: "{{ android_studio_user }}"
      group: "{{ android_studio_user }}"

  - name: "get android studio"
    ansible.builtin.unarchive:
      src: "{{ android_studio_dwl_url }}"
      dest: "{{ android_studio_path_to_install }}"
      remote_src: yes

  - name: "add android studio alias"
    import_role:
      name: "env_vars"
    vars:
      env_vars_list:
        - "export ANDROID_SDK_ROOT='~/Android/Sdk/'"
    tags:
      - android_studio.env

  - name: "add android studio alias"
    import_role:
      name: "env_alias"
    vars:
      env_alias_list:
        - "alias studio='{{ android_studio_path_to_install }}/android-studio/bin/studio.sh'"
        - "alias android-studio='studio'"
    tags:
      - android_studio.env
