---
- name: "install docker dependancies"
  become: yes
  package:
    name:
      - "apt-transport-https"
      - "ca-certificates"
      - "curl"
      - "gnupg"
      - "lsb-release"

- name: "install docker gpg key"
  become: yes
  shell: >
    curl -fsSL {{ docker_gpg_url }}/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
- name:
  become: yes
  shell: >
    echo \
      "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] {{ docker_gpg_url }} \
      $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list
- name: apt update
  become: true
  apt:
    update_cache: yes
