---
- when: tmux_install | bool
  block:
  - name: "install tmux"
    package:
      name:
        - tmux
      state: present
    become: yes

  - name: "create plugin dir: {{ tmux_plugins_dir }}"
    file:
      path: "{{ tmux_plugins_dir }}"
      state: directory
      mode: '0755'
      recurse: yes

  - import_tasks: config.yml

  - name: Git clone plugin
    ansible.builtin.git:
      repo: 'https://github.com/tmux-plugins/{{ item.name }}.git'
      dest: "{{ tmux_plugins_dir }}/{{ item.name }}"
      version: master
    loop: "{{ tmux_plugins }}"
    ignore_errors: yes

# Needed ?
#  - name: source tmux conf
#    command: tmux source-file ~/.tmux.conf
