---
- name: install prerequisite
  become: yes
  package:
    name:
      - ffmpeg
      - v4l2loopback-dkms
    state: present
- name: add php apt-key
  become: yes
  apt_repository:
    repo: ppa:obsproject/obs-studio
    update_cache: yes
- name: apt update
  become: true
  apt:
    update_cache: yes
- name: install obs
  become: yes
  package:
    name:
      - obs-studio
    state: present
