dist: xenial # needed to use python 3.7
language: python
branches:
  only:
    - master
python:
  - 3.7
install:
  - pip install -U pip
  - cd 000-docs
  - pip install -r requirements.txt # install the required packages
script:
  - skip # Travis requires a `script` property, but we do not need it
stages:
  - deploy
jobs:
  include:
    - stage: deploy
      name: Deploy to GitHub Pages
      if: (branch = master) # only deploy if merging on master
      script:
        - make html
        - touch build/html/.nojekyll
      deploy:
        provider: pages # deploy on github pages
        skip_cleanup: true
        github_token: "$token" # defined via the Travis interface
        local_dir: 000-docs/build/html