---
- when: terraform_install | bool
  block:
  - when: terraform_install_by_tfenv | bool
    import_tasks: install_terraform_by_tfenv.yml

  - when: not (terraform_install_by_tfenv | bool)
    import_tasks: install_terraform_s_bin.yml
