---

- name: Install a list of python packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - python
    - python-pip
    - virtualenv
- name: Install a list of python3 packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - python3
    - python3-pip
- name: Install python extension
  pip:
    name:
      - pipenv
    executable: pip3
