---
- name: au cas ou
  debug:
    msg: "si ca marche pas c est qu il manque apt-get install -y software-properties-common python-software-properties"
- name: add git apt-key
  apt_repository:
    repo: ppa:nginx/stable
    update_cache: yes
- name: install git
  apt:
    name: git
- name: make gitconfig
  template:
    src: templates/.gitconfig.j2
    dest: "/home/{{config.user}}/.gitconfig"
    owner: "{{config.user}}"
    group: "{{config.user}}"
    mode: 0644
