---
- name: install npm
  apt:
    name: "npm"
- name: install n
  npm:
    name: n
    global: yes
- name: install node
  command: >
    n stable
- name: install node plugins
  npm:
    name: "{{ item }}"
    global: yes
  with_items:
    - yarn
    - "@angular/cli"

