---
#   ${package} ${package}-fpm ${package}-mysql ${package}-curl ${package}-xml ${package}-mbstring ${package}-zip
- name: au cas ou
  debug:
    msg: "si ca marche pas c est qu il manque apt-get install -y software-properties-common python-software-properties"
- name: au cas ou
  debug:
    msg: "et sudo LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/php"
- name: add php apt-key
  apt_repository:
    repo: ppa:ondrej/php
    update_cache: yes
- name: install php main package
  apt:
    name: "{{ php.main_package }}"
- name: package concatenation
  shell: "echo {{ php.main_package + '-' + item }}"
  with_items: "{{ php.sub_packages }}"
  register: tmp_packages
- name: install php sub packages
  apt:
    name: "{{ item.stdout }}"
  with_items: "{{ tmp_packages.results }}"
# deprecated
#  apt:
#    name: "{{ php.main_package + '-' + item }}"
#  with_items: "{{ php.sub_packages }}"