---
- name: Add user to the docker group
  user:
    name: "{{ user }}"
    groups: docker
    append: yes
  become: yes
- name: "chown/chmod /home/{{ user }}/.docker"
  file:
    path: /home/{{ user }}/.docker
    owner: "{{ user }}"
    group: "{{ user }}"
    recurse: yes
    state: directory
    mode: g+rxw
- name: "chown {{ user }} /var/run/docker.sock"
  file:
    path: /var/run/docker.sock
    owner: "{{ user }}"
    