---
- import_tasks: prerequisites.yml
- import_tasks: config.yml
- import_tasks: install_wp.yml
- import_tasks: init_wp.yml

- name: "Your website"
  debug:
    msg: "Go to {{ wordpress_acces_url }} to see your website"
- name: "Login"
  debug:
    msg: "Go to {{ wordpress_acces_url }}/wp-login.php to go admin interface (default: http://localhost:8080/wp-login.php)"
