---
- name: "Ensure {{ tilt_path_to_install }} exists"
  ansible.builtin.file:
    path: "{{ tilt_path_to_install }}"
    state: directory
    mode: 0755

- name: "Extract {{ tilt_download_url }} in {{ tilt_path_to_install }}"
  ansible.builtin.unarchive:
    src: "{{ tilt_download_url }}"
    dest: "{{ tilt_path_to_install }}"
    remote_src: yes
    mode: 0755
