---
- when: git_install | bool
  block:
  - name: install git
    package:
      name: git

  - import_tasks: config.yml

  - include_tasks: get_project.yml
    loop: "{{ git_projects }}"
    loop_control:
      loop_var: _i_project
