---
- name: install git
  package:
    name: git
- name: make gitconfig
  template:
    src: templates/.gitconfig.j2
    dest: "/home/{{ git_user }}/.gitconfig"
    owner: "{{ git_user }}"
    group: "{{ git_user }}"
    mode: 0644
