---
- name: "ensure '{{ env_alias_file }}' exist"
  copy:
    content: ""
    dest: '{{ env_alias_file }}'
    force: no
    mode: 0755
- name: "add alias in {{ env_alias_file }}"
  ansible.builtin.lineinfile:
    path: "{{ env_alias_file }}"
    line: "{{ i_env_alias_list }}"
  loop: "{{ env_alias_list }}"
  loop_control:
    loop_var: i_env_alias_list
- name: "check alias file is in terminal rc"
  ansible.builtin.lineinfile:
    path: "{{ env_alias_terminal_rc_file }}"
    line: "source {{ env_alias_file }}"
