---
# Be carefull if fail
#sudo update-alternatives --remove python /usr/bin/python
#sudo update-alternatives --remove python3 /usr/bin/python3
#sudo apt remove -y python3.9
#sudo apt autoremove -y
#sudo unlink /usr/bin/python3
#sudo unlink /usr/bin/python
#sudo ln -s /usr/bin/python3.8 /usr/bin/python3
#sudo ln -s /usr/bin/python3.8 /usr/bin/python

- name: Install a list of python3 packages
  become: yes
  apt:
    force: yes
    name: "{{ item }}"
  loop:
    - python3
    - python3-pip
    - "{{ python_specific_version }}"

- name: reinstall python-apt
  become: yes
  apt:
    force: yes
    only_upgrade: no
    name: 
      - "python3-apt"
      - "python3-pil"
    state: present

- name: Alternatives link to specific version
  become: yes
  command: >
    update-alternatives --install /usr/bin/python3 python3 /usr/bin/{{ python_specific_version }} 1

- name: Alternatives link to default version
  become: yes
  command: >
    update-alternatives --install /usr/bin/python python /usr/bin/python3 1

- name: Install ansible in new version
  become: yes
  pip:
    name: "ansible"
    executable: pip3

- name: install katrain dependancies
  become: yes
  package:
    name:
      - xclip

- name: Install python extension
  become: yes
  pip:
    name: "Pillow"
    executable: pip3
    extra_args: -U

- name: Install python extension
  become: yes
  pip:
    name: "{{ python_additional_packages }}"
    executable: pip3
