---
- when: ctlptl_install | bool
  block:
  - name: "create soft dir: {{ ctlptl_path_to_install }}"
    file:
      path: "{{ ctlptl_path_to_install }}"
      state: directory
      mode: '0755'
      recurse: yes

  - name: Download ctlptl
    ansible.builtin.unarchive:
      src: "{{ ctlptl_download_url }}"
      dest: "{{ ctlptl_path_to_install }}"
      remote_src: yes
      extra_opts:
        - ctlptl

  - name: "Add {{ ctlptl_path_to_install }} to path"
    import_role:
      name: "env_vars"
    vars:
      env_vars_list:
        - "export PATH=$PATH:{{ ctlptl_path_to_install }}"
