---
- name: Add groups for dynamic hosts
  hosts: all
  tasks:
    - when:
        - groups['dynamic_inventory'] is defined
        - inventory_hostname in groups['dynamic_inventory']
      ansible.builtin.add_host:
        group: "{{ hosts_organisation_groups[inventory_hostname] + hosts_language_groups[inventory_hostname] + hosts_software_groups[inventory_hostname]}}"
        hostname: "{{ inventory_hostname }}"
      delegate_to: localhost
    - debug:
        var: groups

- name: Installation initial task
  hosts: all
#  roles:
#    - geerlingguy.docker
  tasks:
    - name: "create directory in opt for user"
      ansible.builtin.file:
        path: "/opt/{{ dev_user }}"
        state: directory
        mode: "0755"
        owner: "{{ dev_user }}"
        group: "{{ dev_user }}"
      become: yes

    - import_tasks: tasks/apt_update.yml
      tags: "update"

    - import_tasks: tasks/vital_packages.yml
      tags: "package"

    - import_tasks: tasks/system_packages.yml
      tags: "package"

    - import_role:
        name: "dev_software/zsh"
      tags: "zsh"
    #- import_tasks: tasks/banner.yml

    - import_role:
        name: "gnome"
      tags: "gnome"

    - import_role:
        name: "math_exo"
      tags: "math_exo"

- name: Installation dev roles
  hosts: all
  tasks:
    - import_role:
        name: "dev_software/man"
      tags: "man_config"

    - import_role:
        name: "dev_software/python"
      tags: "python"

    - import_role:
        name: "dev_software/git"
      tags: "git"

    - import_role:
        name: "dev_software/ctlptl"
      tags: "ctlptl"

    - import_role:
        name: "dev_software/direnv"
      tags: "direnv"

    - import_role:
        name: "dev_software/helm"
      tags: "helm"

    - import_role:
        name: "dev_software/kind"
      tags: "kind"

    - import_role:
        name: "dev_software/php"
      tags: "php"

    - import_role:
        name: "dev_software/npm"
      tags: "npm"

    - import_role:
        name: "dev_software/flutter"
      tags: "flutter"

    - import_role:
        name: "dev_software/golang"
      tags: "golang"

    - import_role:
        name: "dev_software/appimage_builder"
      tags: "appimage_builder"

    - import_role:
        name: "tmux"
      tags: "tmux"

    - block:
      - import_tasks: tasks/install_vscode.yml

      - import_role:
          name: "dev_software/vscode"
      tags: "vscode"
    #- import_tasks: tasks/install_atom.yml
    #    # wtf payment required
    # TODO: install docker compose

    - import_role:
        name: "dev_software/docker"
      tags: "docker"

    - import_role:
        name: "dev_software/kubectl"
      tags: "kubectl"

    - import_role:
        name: "dev_software/android_studio"
      tags: "android_studio"

    - import_role:
        name: "anki"
      tags: "anki"

    - import_role:
        name: "dev_software/tilt"
      tags: "tilt"

    - import_role:
        name: "dev_software/rdme_statefull"
      tags: "rdme_statefull"

    - import_role:
        name: "dev_software/terraform"
      tags: "terraform"

    - import_role:
        name: "dev_software/azure_cli"
      tags: "azure_cli"

- name: Installation communication roles
  hosts: all
  tasks:
    - import_role:
        name: "com_software/discord"
      tags: "discord"

    - import_role:
        name: "com_software/slack"
      tags: "slack"

    - import_role:
        name: "com_software/teams"
      tags: "teams"

    - import_role:
        name: "com_software/zoom"
      tags: "zoom"

    - import_role:
        name: "blender"
      tags: "blender"

    - import_role:
        name: "obs"
      tags: "obs"

    - import_role:
        name: "kdenlive"
      tags: "kdenlive"

- name: Installation gogame roles
  hosts: all
  tasks:
    - import_role:
        name: "wine"
      tags: "wine"

    - import_role:
        name: "go_software/go_cgoban"
      tags: "go_cgoban"

    - import_role:
        name: "go_software/go_igs"
      tags: "go_igs"

      # need to be after wine
    - import_role:
        name: "go_software/go_fox"
      tags: "go_fox"

      # need to be after wine
    - import_role:
        name: "go_software/go_drago"
      tags: "go_drago"

- name: Installation custom
  hosts: all
  tasks:
    - import_role:
        name: openvpn
      tags: openvpn
