- name: init chromebook
  hosts: all
  vars_files:
    - vars/playbook.yml
    - vars/template.yml
#  roles:
#    - geerlingguy.docker
  tasks:
    - import_tasks: tasks/apt_update.yml
      tags: "update"
    - import_tasks: tasks/vital_packages.yml
      tags: "package"
    - import_tasks: tasks/system_packages.yml
      tags: "package"
    - import_tasks: tasks/install_zsh_plugin.yml
      tags: "zsh"
    - import_tasks: tasks/install_git.yml
      tags: "git"
    #- import_tasks: tasks/banner.yml
    - name: Include php vars
      tags: "php"
      include_vars: vars/vars-install_php.yml
    - import_tasks: tasks/install_php.yml
      tags: "php"
    - name: Include composer vars  
      tags: "php"
      include_vars: vars/vars-install_composer.yml
    - import_tasks: tasks/install_composer.yml
      tags: "php"
    - import_tasks: tasks/install_npm.yml
      tags: "npm"
    - import_tasks: tasks/install_vscode.yml
      tags: "vscode"
    #- import_tasks: tasks/install_atom.yml
    - name: Include discord vars
      tags: "discord"
      include_vars: vars/vars-install_discord.yml
    - import_tasks: tasks/install_discord.yml
      tags: "discord"
    - import_tasks: tasks/install_slack.yml
      tags: "slack"
    - name: Include ansible_non_root_user.yml vars
      tags: "docker"
      include_vars: vars/vars-ansible_non_root_user.yml
    - import_tasks: tasks/install_docker.yml
      tags: "docker"
    - import_tasks: tasks/non_root_docker_user.yml
      tags: "docker"
    - import_tasks: tasks/install_cgoban.yml
      tags: "cgoban"
