---
direnv_download_url: https://github.com/direnv/direnv/releases/download/v2.32.1/direnv.linux-amd64
direnv_install: no
direnv_path_to_bin: "{{ direnv_path_to_install }}/direnv"
direnv_path_to_install: ~/software/bin
