name: HTCPCP Build

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document to generate toc
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: 000-src/tex/k8s-sumup/
          root_file: src/htcpcp-sumup.tex
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: 000-src/tex/k8s-sumup/
          root_file: src/htcpcp-sumup.tex
      - uses: actions/upload-artifact@v2
        with:
          name: htcpcp-sumup.pdf
          path: 000-src/tex/k8s-sumup/htcpcp-sumup.pdf
